-- MySQL Script generated by MySQL Workbench
-- Fri Nov 19 16:34:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scouts` DEFAULT CHARACTER SET utf8 ;
USE `scouts` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(25) NOT NULL,
  `Contraseña` VARCHAR(10) NOT NULL,
  `NombreCompleto` VARCHAR(100) NOT NULL,
  `Nacimiento` DATE NOT NULL,
  `numTropa` INT NOT NULL,
  `seccion` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`idUsuario`));


-- -----------------------------------------------------
-- Table `mydb`.`Mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensajes` (
  `idMensajes` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(400) NULL,
  `idMensajeAnt` INT NULL,
  PRIMARY KEY (`idMensajes`),
  INDEX `idMensajeAnt_idx` (`idMensajeAnt` ASC),
  CONSTRAINT `idMensajeAnt`
    FOREIGN KEY (`idMensajeAnt`)
    REFERENCES `mydb`.`Mensajes` (`idMensajes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chat` (
  `usuario1` INT NOT NULL AUTO_INCREMENT,
  `ususario2` INT NOT NULL,
  `idMensaje` INT NULL,
  PRIMARY KEY (`usuario1`, `ususario2`),
  INDEX `usuario2_idx` (`ususario2` ASC),
  INDEX `idMensaje_idx` (`idMensaje` ASC),
  CONSTRAINT `usuario1`
    FOREIGN KEY (`usuario1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario2`
    FOREIGN KEY (`ususario2`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMensaje`
    FOREIGN KEY (`idMensaje`)
    REFERENCES `mydb`.`Mensajes` (`idMensajes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Foro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Foro` (
  `idForo` INT NOT NULL AUTO_INCREMENT,
  `tipoDeForo` VARCHAR(40) NULL,
  PRIMARY KEY (`idForo`));


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  `idNxtComentario` INT NULL,
  `idRespuesta` INT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  INDEX `idNxtComentario_idx` (`idNxtComentario` ASC),
  INDEX `idRespuesta_idx` (`idRespuesta` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idNxtComentario`
    FOREIGN KEY (`idNxtComentario`)
    REFERENCES `mydb`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRespuesta`
    FOREIGN KEY (`idRespuesta`)
    REFERENCES `mydb`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `idForo` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `descripcion` VARCHAR(400) NOT NULL,
  `img` VARCHAR(500) NULL,
  `idComentario` INT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `idForo_idx` (`idForo` ASC),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  INDEX `idComentario_idx` (`idComentario` ASC),
  CONSTRAINT `idForo`
    FOREIGN KEY (`idForo`)
    REFERENCES `mydb`.`Foro` (`idForo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuarioP`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idComentario`
    FOREIGN KEY (`idComentario`)
    REFERENCES `mydb`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
